# 
# Master build pipeline
#


trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*
    - fix/*
  paths:
    exclude:
    - README.md
    - LICENSE



extends:
  template: azure-build-publish-pipeline.yml

