# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- stable

resources:
- repo: self

jobs:
- template: azure-build-test.yml

- job: deploy

  pool: 
    vmImage: 'ubuntu-latest'

  variables:
    tag: '$(Build.BuildId)'

  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'WatchServer-Test'
      command: 'buildAndPush'
      dockerfile: '$(Build.SourcesDirectory)/IB.WatchServer.Service/Dockerfile'
      tags: |
        latest
        $(tag)