# 
# Stable build pipeline
#

resources:
  containers:
  # Specify the Docker container hosting the database to be used when running integration tests.
  # 
  - container: 'postgres_linux'
    image: 'postgres:alpine'
    ports:
    - 5432:5432
    env:
      POSTGRES_DB: $(testDatabase)
      POSTGRES_USER: $(testDbUsername)
      POSTGRES_PASSWORD: $(testDbPassword)

trigger:
  branches:
    include:
    - stable
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  testDatabase: 'watch-service-test'
  testDbUsername: 'testdb-user'
  testDbPassword: 'testdb-password'

services:
  pg_server_test: 'postgres_linux'

steps:
- template: azure-build-publish-pipeline.yml