# 
# Master build pipeline
#


trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*
    - fix/*
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'

services:
  pg_server_test: 'postgres_linux'

extends:
  template: azure-build-publish-pipeline.yml

