# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- stable

resources:
- repo: self

jobs:
- template: azure-build-test.yml

- job: deploy
  dependsOn: build

  pool: 
    vmImage: 'ubuntu-latest'

  variables:
    tag: '$(Build.BuildId)'

  steps:
  - pwsh: |
      $year = Get-Date -Format yy
      $day = (Get-Date).DayOfYear
      $version = & git rev-list --count HEAD
      $fullVersion = "1.$year.$day.$version"
      $projFiles = Get-Childitem -Path $(Build.SourcesDirectory) -Include *.csproj -Recurse
      foreach($projFile in $projFiles)
      {
        [xml]$projXml = Get-Content -Path $projFile
	    $projXml.Project.PropertyGroup.AssemblyVersion = $fullVersion
        $projXml.Save($projFile)
      }


  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'ilaverlin/watchserver-test'
      command: 'buildAndPush'
      dockerfile: '$(Build.SourcesDirectory)/IB.WatchServer.Service/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        latest
        $(tag)