# 
# Stable build pipeline
#

trigger:
  batch: true
  branches:
    include:
    - stable
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- template: azure-build-publish-pipeline.yml