{
 "title": "Main Watch Server",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Version", "query": "label_values(version)" }
  ]
 },
 "panels": [
  {
   "title": "Requests (1h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n$__timeGroup(\"RequestTime\", '1h') AS \"time\",\n  count(*) AS \"count\"\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\")\nGROUP BY \"time\"\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Old vs New",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH \n  \"New2\" as (SELECT C.\"RequestTime\"::date as \"time\",\n      Count(distinct(D.\"id\")) as \"New\"\n    FROM \"DeviceInfo\" D inner join \"CityInfo\" C on D.\"id\" = C.\"DeviceInfoId\"\n    WHERE D.\"FirstRequestTime\"::date = C.\"RequestTime\"::date\n    GROUP BY C.\"RequestTime\"::date), \n\n  \"Old2\" as (SELECT C.\"RequestTime\"::date as \"time\",\n    Count(distinct(D.\"id\")) as \"Old\"\n  FROM \"DeviceInfo\" D inner join \"CityInfo\" C on D.\"id\" = C.\"DeviceInfoId\"\n  WHERE\n    D.\"FirstRequestTime\"::date != C.\"RequestTime\"::date --< C.\"RequestTime\"::date - '7 day'::interval\n    GROUP BY C.\"RequestTime\"::date)\nSELECT \"New2\".time, \"New2\".\"New\", \"Old2\".\"Old\", \"New2\".\"New\" + \"Old2\".\"Old\" as \"Total\"  FROM \"New2\" JOIN \"Old2\" ON \"New2\".time = \"Old2\".time\nWHERE \"New2\".time > now() - '1 month'::interval\n"
    }
   ]
  },
  {
   "title": "Weather Providers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(application_weather_request{provider=\"DarkSky\"}[$__range]))",
     "legendFormat": "DarkSky"
    },
    {
     "expr": "sum(delta(application_weather_request{provider=\"OpenWeather\"}[$__range]))",
     "legendFormat": "OpenW..."
    }
   ]
  },
  {
   "title": "Location Cache",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(application_location_request{source_type=\"Database\"}[$__range]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(delta(application_location_request{source_type=\"Remote\"}[$__range]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Exchange Rate Cache",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_exchangerate_request{source_type=\"Memory\"})",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(application_exchangerate_request{source_type=\"Remote\"})",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Services Throughput",
   "type": "bargauge",
   "description": "OW: OpenWeather requests per minute. Max 60\nCC: CurrencyConverter requests per hour. Max 100\nVE: VirtualEarth requests per hour. No limits ",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(application_weather_request{provider=\"OpenWeather\", source_type=\"Remote\"}[10m])*60)",
     "legendFormat": "OW  R/M"
    },
    {
     "expr": "sum(rate(application_exchangerate_request{source_type=\"Remote\"}[1h])*60*60)",
     "legendFormat": "CC R/H"
    },
    {
     "expr": "sum(rate(application_location_request{source_type=\"Remote\"}[$__range])*60*60)",
     "legendFormat": "VE R/H"
    }
   ]
  },
  {
   "title": "Unique Devices",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "WITH \n  \"New\" as (SELECT\n      Count(distinct(D.\"id\")) as \"New\"\n    FROM \"DeviceInfo\" D inner join \"CityInfo\" C on D.\"id\" = C.\"DeviceInfoId\"\n    WHERE\n    $__timeFilter(D.\"FirstRequestTime\")\n    AND  $__timeFilter(C.\"RequestTime\")), \n\n  \"Old\" as (SELECT \n    Count(distinct(D.\"id\")) as \"Old\"\n  FROM \"DeviceInfo\" D inner join \"CityInfo\" C on D.\"id\" = C.\"DeviceInfoId\"\n  WHERE\n    D.\"FirstRequestTime\" < now() - '7 day'::interval\n    AND  $__timeFilter(C.\"RequestTime\"))\nSELECT NOW() AS time, * FROM \"New\", \"Old\"\n\n"
    }
   ]
  },
  {
   "title": "Unique Device :: avg/h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', \"RequestTime\") as time,\n  count(distinct(\"DeviceInfoId\"))\nFROM\n  \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\")\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "Unique Device :: total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  Now() as time,\n  count(distinct(\"DeviceInfoId\"))\nFROM\n  \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\")\n"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "singlestat",
   "description": "Update message had sent",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_httprequests_transactions_per_endpoint_count{ route=\"GET api/v{version:apiVersion}/YAFace/location\"})"
    }
   ]
  },
  { "title": "Watch Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Devices :: window",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  COALESCE(D.\"DeviceName\", 'nil') as \"DeviceName\",\n  count(distinct(D.\"DeviceId\")) as \"Count\"\nFROM\n  \"DeviceInfo\" D JOIN \"CityInfo\" C ON D.\"id\" = C.\"DeviceInfoId\" AND $__timeFilter(C.\"RequestTime\")\n\nGROUP BY \n  D.\"DeviceName\"\nORDER BY \"Count\" desc\n"
    }
   ]
  },
  {
   "title": "Devices Total",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS time,\n  COALESCE(\"DeviceName\", 'nil') as \"DeviceName\",\n  count(distinct(D.\"DeviceId\")) as \"count\"\nFROM\n  \"DeviceInfo\" D JOIN \"CityInfo\" C ON D.\"id\" = C.\"DeviceInfoId\"\n--WHERE\n--  $__timeFilter(\"RequestTime\")\nGROUP BY \n  \"DeviceName\"\nORDER BY \"count\" desc"
    }
   ]
  },
  {
   "title": "Version :: window",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
   "targets": [
    {
     "rawSql": "select\n  COALESCE(\"FaceVersion\", 'nil') as \"Version\",\n  count(distinct(\"DeviceInfoId\")) as \"Count\"\nfrom \"CityInfo\" \n\nWHERE\n  $__timeFilter(\"RequestTime\")\ngroup by \"FaceVersion\"\norder by \"Count\" desc\n\n"
    }
   ]
  },
  {
   "title": "Version Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "rawSql": "select\n  \"FaceVersion\" as \"Version\",\n  count(distinct(\"DeviceInfoId\")) as \"Count\"\nfrom \"CityInfo\" \ngroup by \"FaceVersion\"\norder by \"Count\" desc\n"
    }
   ]
  },
  {
   "title": "Last Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Requests",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"RequestTime\" AS \"Time\",\n  \"DeviceName\",\n  \"CityName\",\t\"Lat\",\t\"Lon\", \"FaceVersion\",\t\"FrameworkVersion\",\t\"CIQVersion\"\nFROM \"CityInfo\" C JOIN \"DeviceInfo\" D on D.\"id\" = C.\"DeviceInfoId\"\nWHERE\n  $__timeFilter(\"RequestTime\")\nORDER BY \"Time\" desc\nLIMIT 20\n"
      }
     ]
    }
   ]
  },
  { "title": "Visual Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Geo visual",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 27 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(\"DeviceInfoId\")) AS metric,\n  max(\"Lat\") AS lat, max(\"Lon\") lon, \"CityName\"\n\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND \"CityName\" is not NULL\nGROUP BY \"CityName\"\n"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"CityName\",\n  count(distinct(\"DeviceInfoId\")) AS \"Count\"\n\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND \"Lat\" IS NOT NULL\nGROUP BY \"CityName\"\nORDER BY \"Count\""
    }
   ]
  }
 ]
}